export enum CardMutationsEnum {
  SET_CARD_LIST_DATA = 'SET_CARD_LIST_DATA',
  SET_ACTIVE_PACKETS = 'SET_ACTIVE_PACKETS',
  SET_COMPLETE_PACKETS = 'SET_COMPLETE_PACKETS',
  SET_MY_INVESTMENTS = 'SET_MY_INVESTMENTS',
  SET_MY_REFERALS_BY_LEVEL = 'SET_MY_REFERALS_BY_LEVEL',
  RESET_CARD_STATE = 'RESET_CARD_STATE',
}
